### PR TITLE
Fix lost `public_transport=station` stops (public transport stops with no role specified), minor fix mapcreator msg

### PR DESCRIPTION
**Pull request by RZR-UA**

### CODE REVIEW

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd/issues/18809

**Comment by RZR-UA** [comment]
Issue #18809 https://www.openstreetmap.org/relation/444659
https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area

Roles defined by public_transport=platform/stop_position are recommended but not required.
Finally, public_transport=station should be considered as a `stop` if it belongs to the stop area(s).

**Comment by RZR-UA** [comment]
Overpass Turbo query to highlight "lost" stations:

```
[bbox:{{bbox}}];

node["public_transport"="station"]->.stations;
rel(bn.stations)["public_transport"="stop_area"]->.areas_with_station;

node["public_transport"="stop_position"]->.positions;
rel(bn.positions)["public_transport"="stop_area"]->.areas_with_positions;

node["public_transport"="platform"]->.platforms;
rel(bn.platforms)["public_transport"="stop_area"]->.areas_with_platforms;

((.areas_with_station; - .areas_with_positions;); - .areas_with_platforms;);

out geom;
```

**Comment by vshcherb** [comment]
Stations should be mapped as ```stop``` to avoid confusion with ```platform``` - https://www.openstreetmap.org/node/2183569935 (example)

**Pull request closed without merging**
