### PR TITLE
Handle paths with quotes in MapCreatorUtilities

### LINKED ISSUE #619: Filenames not escaped in OsmAndMapCreatorUtilities
Cannot process files containing `'` characters, as the argument is not escaped:

https://github.com/osmandapp/OsmAnd-tools/blob/9a74f636f74dca41eb919a21b8b93ae94f8bcb57/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java#L391-L392

Here is the log:

```
[...]
INFO: Task loading_file/extrastoragebig/estratti/output/dati/poly/regioni/pbf/02_Valle d'Aosta - Vallée d'Aoste.osm.pbf is finished 
May 10, 2023 1:31:57 AM net.osmand.obf.preparation.IndexCreator extractOsmToNodesDB
INFO: File parsed : 40291
May 10, 2023 1:31:57 AM net.osmand.impl.ConsoleProgressImplementation finishTask
INFO: Task null is finished 
May 10, 2023 1:31:57 AM net.osmand.obf.preparation.IndexCreator extractOsmToNodesDB
INFO: File indexed : 40291
May 10, 2023 1:31:57 AM net.osmand.obf.preparation.IndexCreator generateIndexes
SEVERE: Log exception
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "Aosta": syntax error)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.throwex(DB.java:374)
        at org.sqlite.NativeDB.prepare(Native Method)
        at org.sqlite.DB.prepare(DB.java:123)
        at org.sqlite.Stmt.execute(Stmt.java:113)
        at net.osmand.obf.preparation.IndexCreator.initDbAccessor(IndexCreator.java:391)
        at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:618)
        at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:538)
        at net.osmand.util.IndexBatchCreator.generateLocalIndex(IndexBatchCreator.java:811)
        at net.osmand.util.IndexBatchCreator.runBatch(IndexBatchCreator.java:387)
        at net.osmand.util.IndexBatchCreator.main(IndexBatchCreator.java:178)
```

I would suggest using the same measures used to fix SQL injection vulnerabilities, such as prepared statements.

### PR DESCRIPTION
**Pull request by frafra**
Should fix #619. Untested.

### CODE REVIEW

**Comment by frafra** [comment]
It looks like this has been fixed in 11be85bb63b590e77b83ecc711386b8aad29ce31 by @Dima-1.

It would be nice to update the issues an PR so to avoid wasting others' people time, and say "thanks" instead of just copy and pasting code from existing PR :D

**Comment by frafra** [comment]
> PR had compilation issues and also runtime exceptions, so it's better of course for us to plan that issue otherwise the organizational process becomes messy

I am sorry, I have no clue about what you mean with "plan that issue" and how leaving a comment on an issue or PR would have made your organizational process messy, nor how removing authorship could have make things better.

The draft PR had these issues (of course, it was a draft, I wrote that I needed to test it), and I fixed them a few days later, as soon as I had enough free time to understand how to compile and test the code, since there is no documentation on dependencies or the build process. I just wasted hours trying to do my first contribution to OsmAnd-tools because no one took 10 seconds to write "thanks, we are working on it" or "ok, we will test your PR as soon as you mark it as ready". In addition to that, instead of just amending the commit having a bit of recognition (such as co-authored commit), the code has been just copied-and-paste, and fixed. I am sure you can understand why a contributor can be frustrated by that.

**Comment by vshcherb** [comment]
Thanks for your contribution, you did a good job. It was not complete. Sometimes incomplete work causes other people to complete, so I would say we should say thank to each other so every work is appreciated.

**Comment by frafra** [comment]
Thanks for the kind words, I agree, and I am glad that you fixed that so quickly after my pull/merge request. I hope that my criticism for the method can be seen as a way to get better at working with external contributions, and not as a personal criticism. Have a good day!

**Pull request closed without merging**
