### PR TITLE
Update indexes.xml

### PR DESCRIPTION
**Pull request by pedronavajo**
Added Papua New Guinea in Oceania region

### CODE REVIEW

**Comment by xmd5a2** [comment]
Papua New Guinea is already in Australia-Oceania and Oceania maps

**Comment by pedronavajo** [comment]
Thanks. I want to add it as a separate country, as it is not available yet
in the countries list. I am following the instructions here to do so:
http://osmand.net/help/TechnicalArticles.html#Country_Polygon_Creation

On 18 May 2015 at 16:53, xmd5a <notifications@github.com> wrote:

> Papua New Guinea is already in Australia-Oceania and Oceania maps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/OsmAnd-tools/pull/100#issuecomment-102939906>
> .
>



-- 
"Mi único límite es el cielo abierto.  Cuando dices que algo es imposible,
lo has hecho imposible" Bruce Lee

**Comment by xmd5a2** [comment]
Papua New Guinea OSM extract is absent at geofabric.de, so if we want to add it as separate country we need to convert it on our server. But it is quite loaded and it is undesirable to do this with no particular reason.

**Comment by pedronavajo** [comment]
I am working and living in PNG. We do a massive amount of field activity,
including in my case updating OSM. I thought it would be nice to be able to
download the country by itself, and teach my colleagues on how to use
OSMAND without the burden of asking them to download the 470+Mbytes file in
their phone. This way we could update several regions in OSM, not just
mine. Any other suggestion on how to do so?

On 18 May 2015 at 17:06, xmd5a <notifications@github.com> wrote:

> Closed #100 <https://github.com/osmandapp/OsmAnd-tools/pull/100>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/OsmAnd-tools/pull/100#event-307082472>.
>



-- 
"Mi único límite es el cielo abierto.  Cuando dices que algo es imposible,
lo has hecho imposible" Bruce Lee

**Comment by xmd5a2** [comment]
Why download 470+ Mb? Download Oceania_australia-oceania_2.obf.zip , it is only 34Mb. Just checked it by myself.

**Comment by pedronavajo** [comment]
Yes, correct. But maybe you can orient me on this: in my mobile, I just
downloaded "Australia and Oceania" using the app and the data downloaded
totals 632.9 MB. I did this only two hours ago. I want to reduce this
download to a reasonable amount. Where does the difference between 34mb
file and the 632 mb files comes from? Thanks

On 18 May 2015 at 17:18, xmd5a <notifications@github.com> wrote:

> Why download 470+ Mb? Download Oceania_australia-oceania_2.obf.zip , it is
> only 34Mb. Just checked it by myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/OsmAnd-tools/pull/100#issuecomment-102945544>
> .
>



-- 
"Mi único límite es el cielo abierto.  Cuando dices que algo es imposible,
lo has hecho imposible" Bruce Lee

**Comment by xmd5a2** [comment]
Please note that we have TWO maps: 1)Australia and Oceania 2)Oceania

**Pull request closed without merging**
